
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1ERXhNREV4TURVeU5sb1hEVE15TURFd09ERXhNRFV5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT3NaCmxFZUlXUko3R0phNWkwU3JEbXpsUVNuVzdQRDlPQU52STBWSjVlcVB1WEwxYkZqRWNsUjkwTEdnckQ0THB0SEQKcEN1SGwyQ0gweXlLQjZuOHY2eTQ0U2tCazhNdTdKSlhFUkUxcE9WN3kwTGozNnYyVloyOGFvL2x3U01uVzViYwpITkVjazh5emVBekM2SHJTZjN5am9JZW5GZkUzMGZtM2x4b3Vod1lTelRtVi9jYlZvOVZlMDdSaFZtSTBpS1EzCk42bzBMMmdZRXVpVTlmVEN5aGFremZMcUZTZ3dqTkl5UldzS1AwMXlFNzFxa3NPUG84OVR1cUpzandGQmo1U3YKTTI5T3QwR08zZnJZRDl0VFdEM2NsRUFUZFduK1VEbjV4eTdGSko0NGswbzR2QysxanROMlNHVWRIWllKRUdXWApWUWt0dXhOYnQ4Z0dqTTZ6dWtNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCWVJhTTZkRUJOdW1NSlZOZWNVNWVCT0FmYmlNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSGhNQWZVdWEvbWVJN2JDRGhHMAozNUxKZnlyd1lzNW92Q3BOUThUd1htc29wM1ppWlVUMFg1aUlnQk9UN2F3SDIyT21EN25rdk5VUG9VMU1PN0hKCmFSZTNSTy9LQkNFMjZiZWttMmNOT1pWQlpUMllBZUY0VDNvKzVtSlhNa09CS0p6Y29EVlFMOHF6N2JXZis5TEIKYlFVR283ZzAwejZYYkI0SkxUQkNyZE9DZEVzYjI2Y0V1eUFjVDVVd21TK2FTWDExUnhEVjVrdTJQSmFpd1NoKwpwaWJzbmlWdktVdzdHN2t0bzNRQ1JiU1Jra3VXMmljQ25HOWJrc3JtWTY0dGJQUUx4aWhOa3RHam5BQU1udThICjBzai9YNVJ6RUdmSmpXTTNreEMzNHpic0hxRmY4UHkzQWlsL1hrSEVtT2VDd1QxWkxPMm9SRG1KeDIyZ1lTVysKRGEwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://22218c87-e2e1-4526-9141-7e7a6225604b.eu-west-1.linodelke.net:443
  name: lke49038

users:
- name: lke49038-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkNRaml4Qm5WbTFuM2hBWHZYWXhyTWM0blViSFpHLWRVdkxxX1lnVWtCRWMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcGI1dmwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNDljY2ZkOGMtNDdiOC00MDlhLTg0YmMtZjc4YTQyMjk4ZDk5Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.N8xjd1VXdcAmNuaVqVU-ADwuJGrmzasw4kaTPyW2UbCBiOt9wSZebDJS2PsfBaI0c2uKZjDbANqjUgQONEGuspCVYFzo2G5x8C319sD3MV22z7ZS2yOSc_lKWk0B_tA0FExaqpRnV5j3EbPVmNGzHWnZ67bdzDtZH_BgGDkp3iaLGUd7A5hyUXQt0rAM6_fKwzW62gdThhT9EPJNSiT6AuzoJza5nEq8WzYijKvQkKip1Ba6X8FoaKvTp3FJA6ZeD5bw5hLDwVLIvGsfmL1_1-4aBw86l8xegpCH19Gc9GF_AeQ4LghEEwkdyNYZ4qUVuWlxi778ZywK8xWegDXrSg

contexts:
- context:
    cluster: lke49038
    namespace: default
    user: lke49038-admin
  name: lke49038-ctx

current-context: lke49038-ctx
